

openapi: 3.0.0
info:
  title: todoList
  description: todoList app API
  version: 0.1.9

servers:
  - url: https://parkingapp-9o28.onrender.com/api
    description: Production server
  - url: http://localhost:3000/api
    description: Local server

paths:
  /costumers:
    get:
      tags:
        - costumer
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /addcustomers:
    post:
      tags:
        - customers
      requestBody:
        description: Add customer
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerInput"
      responses:
        "201":
          description: Customer added successfully